version: '3.8'

services:
  # 1. Tu Sonda en Go (La protagonista)
  net-sentinel:
    image: ghcr.io/benjppcesp/net-sentinel:latest
    container_name: net-sentinel
    restart: always # Si falla, se reinicia sola 
    ports:
      - "2112:2112"
    environment:
      - TARGET_URL=https://www.google.com
    networks:
      - monitoring-net

  # 2. Watchtower 
  # Este contenedor vigila si subimos cambios  a GitHub.
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup # Revisa cada 60 seg y borra im√°genes viejas
    networks:
      - monitoring-net

  #Prometheus localmente para ver que funciona
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring-net

networks:
  monitoring-net:
    driver: bridge
